title: Some things change
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2096774
  brandStrength: 0.1875
  lightness: 0.7903225
  brandColors:
    - '#EAEAE9'
    - '#7788A3'
    - '#4B5C77'
    - '#1F2F4C'
    - '#030E2F'
  rhythmicContrast: 0.1248507
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Some things change
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5681003
layout_spectrum: 0.2894727219827473
