name: Some things change
favicon: null
layout_spectrum: 0.2894727219827473
typography_spectrum: 0.5208315930794924
title: Some things change
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.17526567331515253
  lightness: 0.7159993541426957
  saturation: 0.30049560219049454
  rhythmicContrast: 0.07777086342684925
purpose: []
